events {
  worker_connections 1024;
}

http {
  upstream web_server {
    server web:8000;
  }

  server {
    listen 8080;
    listen [::]:8080;
    include /etc/nginx/mime.types;


    location /static/ {
      alias /code/staticfiles/;
      add_header Access-Control-Allow-Origin *;
      #add_header Content-Security-Policy "connect-src 'self' http://57.128.166.240:3000 http://192.168.10.6:5173; http://localhost:5173;";
    }

    location /media/ {
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type';
        add_header 'Content-Length' 0;
        add_header 'Content-Type' 'text/plain';
        return 204;
      }
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type';
      alias /code/media/;
      #add_header Access-Control-Allow-Origin *;
      #add_header Content-Security-Policy "connect-src 'self' http://57.128.166.240:3000 http://192.168.10.6:5173 http://localhost:5173; ";
    }


    location / {
      proxy_pass http://web_server;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      #X-Real-IP
      proxy_set_header X-Real-IP $remote_addr;
      #X-Forwarded-Proto
      proxy_set_header X-Forwarded-Proto $scheme;
      #X-Forwarded-Host
      proxy_set_header X-Forwarded-Host $host;
      #X-Forwarded-Port
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_redirect off;

      #add http_host : "HTTP_HOST": "192.168.10.5:8002",
      #proxy_set_header HTTP_HOST $http_host;

      #set body size 100MB
      client_max_body_size 100M;
    }
  }
}
